theme: jekyll-theme-cayman
title: Midgard - ADA Stake Pool
tagline: HODLing ADA, but not staking it is leaving money on the table.
description: HODLing ADA, but not staking it is leaving money on the table.
google_analytics: G-KR0CRZZ743
author: Kjartan Sverrisson
url: https://midgard.digital/
logo: /assets/img/midgard-logo-social-tiny.jpg
page_excerpts: true
is_home: true

# social
image: /assets/img/midgard-fb-cover-tiny.jpg

twitter:
  username: ADAMidgard
  card: summary

social:
  name: kjartans
  links:
    - https://twitter.com/ADAMidgard
    - https://t.me/midgardpool
    - https://twitter.com/kjartans
    - https://www.facebook.com/kjartansverrisson
    - https://www.linkedin.com/in/kjartansverrisson
   
