theme: jekyll-theme-cayman
title: Midgard ADA Staking Pool
description: Your finiancial freedom is our goal 
google_analytics: G-KR0CRZZ743
url: https://midgard.digital/

# social
image: /assets/img/cardano-eur.jpg

twitter:

  username: ADAMidgard
  card: HODLing ADA, but not staking is leaving money on the table.